/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ_Song_24.c                                          *
* Font:        ËÎÌå                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\³£ÓÃ×Ö-24.txt    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_Song_24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_4F4D[ 96] = { /* code 4F4D */
  ________,________,________,________,
  ______XX,________,________,________,
  ______XX,X____XX_,________,________,
  ______XX,_____XXX,________,________,
  ______XX,______XX,________,________,
  _____XXX,______XX,________,________,
  _____XX_,________,___XXX__,________,
  ____XXX_,XXXXXXXX,XXXXXXX_,________,
  ____XXX_,________,________,________,
  ____XXX_,________,__XXX___,________,
  ___XXXX_,__XX____,_XXX____,________,
  __XX_XX_,__XX____,_XXX____,________,
  __XX_XX_,___XX___,_XX_____,________,
  _XX__XX_,___XX___,_XX_____,________,
  _____XX_,___XXX__,_XX_____,________,
  _____XX_,___XXX__,XXX_____,________,
  _____XX_,___XXX__,XX______,________,
  _____XX_,____XX__,XX______,________,
  _____XX_,________,XX______,________,
  _____XX_,_______X,X_______,________,
  _____XX_,_______X,X___XXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  _____XX_,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_5BB9[ 96] = { /* code 5BB9 */
  ________,________,________,________,
  ________,__XX____,________,________,
  ________,___XXX__,________,________,
  ________,___XXX__,________,________,
  ________,____XX__,____XX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XX___,________,___XX___,________,
  __XXX__X,XX____XX,X_______,________,
  ______XX,X__XXX__,XXX_____,________,
  _____XXX,___XXX__,_XXXX___,________,
  ____XXX_,__XXXX__,__XXX___,________,
  ___XX___,_XXX_XX_,___XX___,________,
  ________,XXX___XX,________,________,
  _______X,XX_____X,XX______,________,
  ______XX,X_______,XXXX____,________,
  _____XXX,X_______,XXXXXXXX,________,
  ___XXX_X,XXXXXXXX,XXX_XX__,________,
  _XXX___X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,XXXXXXXX,XX______,________,
  _______X,X_______,XX______,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_65AD[ 96] = { /* code 65AD */
  ________,________,________,________,
  ________,________,________,________,
  ________,XXX_____,____XX__,________,
  ___XX___,XX______,_XXXXXX_,________,
  ___XX___,XX_XX_XX,XX______,________,
  ___XXXX_,XX_XXXXX,________,________,
  ___XX_XX,XX_XX_XX,________,________,
  ___XX_XX,XXXX__XX,________,________,
  ___XX___,XX____XX,________,________,
  ___XX___,XX_XXXXX,____XXX_,________,
  ___XXXXX,XXXX_XXX,XXXXX___,________,
  ___XX__X,XXX___XX,___XX___,________,
  ___XX__X,XXXX__XX,___XX___,________,
  ___XX_XX,XX_XX_XX,___XX___,________,
  ___XX_XX,XX_XXXXX,___XX___,________,
  ___XXXX_,XX__XXXX,___XX___,________,
  ___XXXX_,XX____XX,___XX___,________,
  ___XXX__,XX____XX,___XX___,________,
  ___XX___,XX___XX_,___XX___,________,
  ___XX___,__XX_XX_,___XX___,________,
  __XXXXXX,XXXXXX__,___XX___,________,
  ________,___XX___,___XX___,________,
  ________,__XX____,___XX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_7535[ 96] = { /* code 7535 */
  ________,________,________,________,
  ________,________,________,________,
  ________,___XXX__,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XX__,___XX___,__XX____,________,
  ____XXXX,XXXXXXXX,XXXX____,________,
  ____XX__,___XX___,________,________,
  ________,___XX___,____XX__,________,
  ________,___XX___,____XX__,________,
  ________,___XX___,_____XX_,________,
  ________,___XXX__,____XXX_,________,
  ________,____XXXX,XXXXXX__,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_77ED[ 96] = { /* code 77ED */
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,________,____XX__,________,
  ____XXX_,________,___XXXX_,________,
  ____XX__,___XXXXX,XXXX____,________,
  ____XX__,________,________,________,
  ___XXXXX,XXX_____,________,________,
  ___XX_XX,____XX__,___XX___,________,
  __XX__XX,____XXXX,XXXXX___,________,
  __XX__XX,____XX__,___XX___,________,
  ______XX,____XX__,___XX___,________,
  ______XX,_XX_XX__,___XX___,________,
  __XXXXXX,XXXXXX__,___XX___,________,
  ______XX,____XXXX,XXXXX___,________,
  _____XXX,____XX__,___XX___,________,
  _____XXX,________,__XX____,________,
  _____XXX,XX__XX__,__XXX___,________,
  _____XX_,XXX__XX_,__XX____,________,
  ____XXX_,_XX__XX_,_XX_____,________,
  ____XX__,_XX__XX_,_XX_____,________,
  ___XXX__,_____XX_,XX___XX_,________,
  ___XX___,_XXXXXXX,XXXXXXX_,________,
  __XX____,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_8DEF[ 96] = { /* code 8DEF */
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,X_______,________,
  ___XX___,XXX__XXX,________,________,
  ___XXXXX,XX___XX_,___XXX__,________,
  ___XX___,XX___XXX,XXXXX___,________,
  ___XX___,XX__XXX_,__XXX___,________,
  ___XX___,XX__XXX_,__XX____,________,
  ___XX___,XXXXX_XX,_XX_____,________,
  ___XXXXX,XXXX___X,XXX_____,________,
  ___XX_XX,__XX___X,XX______,________,
  ______XX,_______X,XXXX____,________,
  ______XX,______XX,__XXX___,________,
  ___XX_XX,XXX_XXX_,___XXXXX,________,
  ___XX_XX,___XXXX_,___XXXX_,________,
  ___XX_XX,__XX_XXX,XXXXXX__,________,
  ___XX_XX,_____XX_,___XX___,________,
  ___XX_XX,_____XX_,___XX___,________,
  ___XX_XX,_XX__XX_,___XX___,________,
  ___XXXXX,XX___XX_,___XX___,________,
  _XXXXX__,_____XX_,___XX___,________,
  ________,_____XXX,XXXXX___,________,
  ________,____XXX_,___XX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_9519[ 96] = { /* code 9519 */
  ________,________,________,________,
  ________,________,________,________,
  _____XX_,_____XXX,_XXX____,________,
  ____XXX_,_____XX_,_XXX____,________,
  ____XXX_,_____XX_,_XXX____,________,
  ____XX__,XX___XX_,_XXXXX__,________,
  ____XXXX,XXXXXXXX,XXXXX___,________,
  ___XX___,_____XX_,_XXX____,________,
  ___XX___,_____XX_,_XXX____,________,
  __XX___X,XX___XX_,_XXX_XX_,________,
  __XXXXXX,_XXXXXXX,XXXXXXXX,________,
  _XX__XX_,________,________,________,
  _____XX_,________,________,________,
  _____XX_,XX_XXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXX__,___XX___,________,
  _____XX_,___XXX__,___XX___,________,
  _____XX_,___XXX__,___XX___,________,
  _____XX_,___XXXXX,XXXXX___,________,
  _____XX_,___XXX__,___XX___,________,
  _____XX_,XX_XXX__,___XX___,________,
  _____XXX,X__XXX__,___XX___,________,
  ____XXX_,___XXXXX,XXXXX___,________,
  ________,___XXX__,___XX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_24_963B[ 96] = { /* code 963B */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___XXXXX,XX_XXXXX,XXXXX___,________,
  ___XX__X,XX_XX___,__XXX___,________,
  ___XX__X,X__XX___,__XXX___,________,
  ___XX_XX,___XX___,__XXX___,________,
  ___XX_XX,___XX___,__XXX___,________,
  ___XX_XX,___XX___,__XXX___,________,
  ___XXXX_,___XXXXX,XXXXX___,________,
  ___XX_XX,___XX___,__XXX___,________,
  ___XX__X,X__XX___,__XXX___,________,
  ___XX___,XX_XX___,__XXX___,________,
  ___XX___,XX_XX___,__XXX___,________,
  ___XX___,XX_XX___,__XXX___,________,
  ___XX___,XX_XXXXX,XXXXX___,________,
  ___XXXXX,XX_XX___,__XXX___,________,
  ___XX_XX,X__XX___,__XXX___,________,
  ___XX___,___XX___,__XXX___,________,
  ___XX___,___XX___,__XXX___,________,
  ___XX___,___XX___,__XXXXX_,________,
  ___XX__X,XXXXXXXX,XXXXXXXX,________,
  ___XX___,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHZ_Song_24_CharInfo[8] = {
   {  25,  25,  4, acGUI_FontHZ_Song_24_4F4D } /* code 4F4D */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_5BB9 } /* code 5BB9 */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_65AD } /* code 65AD */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_7535 } /* code 7535 */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_77ED } /* code 77ED */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_8DEF } /* code 8DEF */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_9519 } /* code 9519 */
  ,{  25,  25,  4, acGUI_FontHZ_Song_24_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop8 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop7 = {
   0x9519 /* first character */
  ,0x9519 /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop6 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop5 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop4 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop3 = {
   0x65AD /* first character */
  ,0x65AD /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop2 = {
   0x5BB9 /* first character */
  ,0x5BB9 /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_24_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontHZ_Song_24_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ_Song_24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_Song_24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ_Song_24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

