/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ_Song_32.c                                          *
* Font:        ËÎÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\wujun-sz\Desktop\³£ÓÃ×Ö-32.txt         *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_Song_32;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_32_5B9A[165] = { /* code 5B9A */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,______XX,________,________,________,
  ________,______XX,X_______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,________,XX______,___XX___,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  _____XX_,________,________,__XXXX__,________,
  ____XXX_,________,________,_XXX____,________,
  ___XXXX_,________,________,_XX_____,________,
  ___XXXX_,________,________,XX______,________,
  ________,________,________,XXX_____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _____XX_,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,XX_____X,XX______,________,________,
  ________,XXXX___X,XX______,________,________,
  ________,XXX____X,XX_____X,XX______,________,
  _______X,XX_____X,XXXXXXXX,XXX_____,________,
  _______X,XX_____X,XX______,________,________,
  _______X,XX_____X,XX______,________,________,
  _______X,XXX____X,XX______,________,________,
  ______XX,X_XX___X,XX______,________,________,
  ______XX,X__XX__X,XX______,________,________,
  _____XXX,____XXXX,XX______,________,________,
  _____XX_,_____XXX,XX______,________,________,
  ____XX__,______XX,XXXXXXXX,XXXXXX__,________,
  ___XX___,________,_XXXXXXX,XXXXX___,________,
  __XX____,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_32_6570[165] = { /* code 6570 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,_XXX____,____XXX_,________,________,
  ________,_XXXX__X,X___XXXX,________,________,
  ____XXX_,_XXX___X,XX__XXX_,________,________,
  _____XXX,_XXX__XX,X__XXX__,________,________,
  _____XXX,XXXX__XX,___XXX__,________,________,
  ______XX,_XXX_XX_,___XXX__,________,________,
  ______XX,_XXXXX_X,X__XX___,____XX__,________,
  ________,_XXX__XX,XXXXX___,___XXXX_,________,
  ___XXXXX,XXXXXXX_,_XXXXXXX,XXXX____,________,
  ________,XXXX____,__XXX___,_XXX____,________,
  _______X,XXXXXXX_,_XXXX___,_XXX____,________,
  ______XX,XXXX_XXX,_XXXX___,_XXX____,________,
  _____XXX,_XXX__XX,XX_XX___,_XXX____,________,
  ____XX__,_XXX____,XX_XX___,_XX_____,________,
  ___XX___,_XX____X,X___XX__,XXX_____,________,
  __XX____,_XXX____,____XX__,XXX_____,________,
  ________,XXXX__XX,____XX__,XXX_____,________,
  ________,XXX___XX,X___XX__,XXX_____,________,
  ___XXXXX,XXXXXXXX,X___XXXX,XX______,________,
  _______X,XX___XXX,_____XXX,XX______,________,
  ______XX,X____XX_,_____XXX,XX______,________,
  ______XX,X___XXX_,_____XXX,X_______,________,
  ________,XXXXXX__,_____XXX,X_______,________,
  ________,__XXXXXX,____XXXX,XX______,________,
  ________,_XXX_XXX,X__XXX__,XXX_____,________,
  _______X,XXX____X,X_XXX___,XXXXX___,________,
  ______XX,X_______,_XXX____,_XXXXXXX,________,
  ___XXXX_,_______X,XX______,___XXX__,________,
  __XX____,_____XXX,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_32_70B9[165] = { /* code 70B9 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,_______X,X_______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,_XXX____,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  ________,_______X,XX______,________,________,
  _______X,XX_____X,XX_____X,XX______,________,
  _______X,XXXXXXXX,XXXXXXXX,XXX_____,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XXXXXXXX,XXXXXXXX,XX______,________,
  _______X,XX______,_______X,XX______,________,
  _______X,XX______,_______X,X_______,________,
  ________,________,________,________,________,
  ________,___XX___,________,_XX_____,________,
  ______XX,____XX__,__XXX___,_XXX____,________,
  ______XX,____XXX_,___XXX__,__XXX___,________,
  _____XXX,____XXXX,___XXX__,___XXX__,________,
  ____XXX_,_____XXX,___XXX__,___XXX__,________,
  ___XXXX_,_____XX_,____XX__,___XXX__,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_32_8282[165] = { /* code 8282 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,___XXX__,____XXX_,________,________,
  ________,___XXX__,____XXX_,________,________,
  ________,___XXX__,____XXX_,___XX___,________,
  ________,___XXX__,____XXX_,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXX__,____XXX_,________,________,
  ________,___XXX__,____XXX_,________,________,
  ________,___XXX__,____XXX_,________,________,
  ________,___XXX__,____XX__,________,________,
  ________,________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  _____XX_,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,________,XXX_____,________,
  ________,_____XXX,__XX____,XXX_____,________,
  ________,_____XXX,___XXXXX,XXX_____,________,
  ________,_____XXX,______XX,XX______,________,
  ________,_____XXX,_______X,X_______,________,
  ________,_____XXX,________,________,________,
  ________,_____XXX,________,________,________,
  ________,_____XXX,________,________,________,
  ________,_____XX_,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_Song_32_9501[165] = { /* code 9501 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ______XX,________,____XX__,________,________,
  ______XX,XX______,____XXXX,________,________,
  ______XX,X_____XX,____XXX_,__XXX___,________,
  ______XX,X______X,XX__XXX_,__XXX___,________,
  _____XXX,___XX___,XXX_XXX_,_XXX____,________,
  _____XXX,__XXXX__,XXX_XXX_,_XX_____,________,
  _____XXX,XXXXXXX_,XXX_XXX_,XX______,________,
  ____XXX_,________,_XX_XXXX,X_______,________,
  ____XX__,________,____XXX_,________,________,
  ____XX__,_______X,XX__XXX_,__XXX___,________,
  ___XX___,__XXX__X,XXXXX_XX,XXXXX___,________,
  ___XXXXX,XXX____X,XX______,__XX____,________,
  __XX__XX,X______X,XX__XX__,__XX____,________,
  _XX___XX,X______X,XX__XXXX,__XX____,________,
  ______XX,X______X,XX__XXX_,__XX____,________,
  ______XX,X__XX__X,XX__XXX_,__XX____,________,
  _XXXXXXX,XXXXXX_X,XX__XXX_,__XX____,________,
  __XX__XX,X______X,XX__XXX_,__XX____,________,
  ______XX,X______X,XX__XXX_,__XX____,________,
  ______XX,X______X,XX__XXX_,__XX____,________,
  ______XX,X______X,XX__XXX_,__XX____,________,
  ______XX,X___XX_X,X___XX__,__XX____,________,
  ______XX,X__XX___,___XXX__,________,________,
  ______XX,XXXX____,___XXX_X,XX______,________,
  ______XX,XXX_____,__XXX___,XXXXX___,________,
  ______XX,XX______,_XXX____,__XXXX__,________,
  _______X,X______X,XX______,___XXXX_,________,
  ________,_____XXX,________,____XXX_,________,
  ________,_XXXXX__,________,_____XX_,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHZ_Song_32_CharInfo[5] = {
   {  33,  33,  5, acGUI_FontHZ_Song_32_5B9A } /* code 5B9A */
  ,{  33,  33,  5, acGUI_FontHZ_Song_32_6570 } /* code 6570 */
  ,{  33,  33,  5, acGUI_FontHZ_Song_32_70B9 } /* code 70B9 */
  ,{  33,  33,  5, acGUI_FontHZ_Song_32_8282 } /* code 8282 */
  ,{  33,  33,  5, acGUI_FontHZ_Song_32_9501 } /* code 9501 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_32_Prop5 = {
   0x9501 /* first character */
  ,0x9501 /* last character  */
  ,&GUI_FontHZ_Song_32_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_32_Prop4 = {
   0x8282 /* first character */
  ,0x8282 /* last character  */
  ,&GUI_FontHZ_Song_32_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ_Song_32_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_32_Prop3 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontHZ_Song_32_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ_Song_32_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_32_Prop2 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontHZ_Song_32_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ_Song_32_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ_Song_32_Prop1 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontHZ_Song_32_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ_Song_32_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_Song_32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ_Song_32_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

