/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "k_storage.h"
#include "wt_task_gui.h"
#include "wt_bsp_key_led.h"
#include "k_rtc.h"
#include "wt_task_wireselfcheck.h"
#include "verision.h"

#pragma diag_suppress 870 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_COPYRIGHT     (GUI_ID_USER + 0x11)
#define ID_TEXT_SOFTWRE     (GUI_ID_USER + 0x15)
#define ID_TEXT_HARDWARE     (GUI_ID_USER + 0x16)
#define ID_TEXT_WEBSITE     (GUI_ID_USER + 0x17)
#define ID_TEXT_MAC     (GUI_ID_USER + 0x18)
#define ID_TEXT_TUNNEL     (GUI_ID_USER + 0x19)
#define ID_TEXT_MACVAL     (GUI_ID_USER + 0x1A)
#define ID_TEXT_TUNEVAL     (GUI_ID_USER + 0x1B)
#define ID_TEXT_ADDR     (GUI_ID_USER + 0x1C)
#define ID_TEXT_ADDRVAL     (GUI_ID_USER + 0x1D)
#define ID_TEXT_BOARD     (GUI_ID_USER + 0x1E)
#define ID_TEXT_BOARDSTAT     (GUI_ID_USER + 0x1F)
#define ID_TEXT_TRANSMIT     (GUI_ID_USER + 0x20)
#define ID_TEXT_TRANSMITSTAT     (GUI_ID_USER + 0x21)

extern GUI_CONST_STORAGE GUI_BITMAP bm_ICO_Info;  //wujun added
extern GUI_CONST_STORAGE GUI_BITMAP bm_logo_lzy115x84;
extern char *itoa(int num, char *str, int radix);
extern uint32_t wheel_value;
extern uint8_t WT_Config_Read(void);

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos);

K_ModuleItem_Typedef  wt_info =
{	
	6,
	"信息",
	&bm_ICO_Info,	
	//&CreateSystemInfo,
	Startup,
	0,
};

//SystemSettingsTypeDef settings;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
/*
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 25, 480, 222, 0, 0x0, 0 },
	{ LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 0, 480, 222, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
*/

#define ID_IMAGE_0     			(GUI_ID_USER + 0x10)
#define ID_TEXT_0     			(GUI_ID_USER + 0x11)
#define ID_MULTIEDIT_0     	(GUI_ID_USER + 0x12)
#define ID_BUTTON_0     		(GUI_ID_USER + 0x13)
#define ID_TEXT_1 					(GUI_ID_USER + 0x15)
#define ID_TEXT_2 					(GUI_ID_USER + 0x16)

//#define ID_TEXT_BOARD           (GUI_ID_USER + 0x04)
#define ID_TEXT_CORE            (GUI_ID_USER + 0x05)
#define ID_TEXT_CPU             (GUI_ID_USER + 0x06)
#define ID_TEXT_VERSION         (GUI_ID_USER + 0x07)
//#define ID_TEXT_COPYRIGHT       (GUI_ID_USER + 0x08)
#define ID_MULTIPAGE            (GUI_ID_USER + 0x0A)
#define ID_IMAGE_LOGO           (GUI_ID_USER + 0x0B)    


/*********************************************************************
*
*       _aDialog
*
* Purpose
*   Dialog resource using a WINDOW widget
*/
static const GUI_WIDGET_CREATE_INFO _aDialog[] = 
{
  
  { WINDOW_CreateIndirect, "System", ID_WINDOW_0, 0, 0, 480, 222, 0, 0x0, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE, 0, 0, 480, 222, 0, 0x0, 0 },  
};

static const GUI_WIDGET_CREATE_INFO _aDialogSystemInformation[] = {
  { WINDOW_CreateIndirect, "System Information", 0, 0,   0, 480, 222, FRAMEWIN_CF_MOVEABLE },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 18, 0, 115, 84, 0, 0, 0 },
  { TEXT_CreateIndirect, "soft-verion", ID_TEXT_SOFTWRE, 18, 100, 200, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "copyright", ID_TEXT_COPYRIGHT, 18, 125, 210, 35, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "website", ID_TEXT_WEBSITE, 18, 150, 200, 20, 0, 0x64, 0 },
	
  { TEXT_CreateIndirect, "hardware ver", ID_TEXT_HARDWARE, 260, 20, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "MAC", ID_TEXT_MAC, 260, 45, 58, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "MAC val", ID_TEXT_MACVAL, 325, 45, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Tunnel", ID_TEXT_TUNNEL, 260, 70, 58, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Tunnel val", ID_TEXT_TUNEVAL, 325, 70, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Addr", ID_TEXT_ADDR, 260, 95, 58, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Addr val", ID_TEXT_ADDRVAL, 325, 95, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "board", ID_TEXT_BOARD, 260, 120, 58, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "board stat", ID_TEXT_BOARDSTAT, 325, 120, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Transmit", ID_TEXT_TRANSMIT, 260, 145, 58, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "transmmit stat", ID_TEXT_TRANSMITSTAT, 325, 145, 80, 20, 0, 0x0, 0 },

};

//static const GUI_WIDGET_CREATE_INFO _aDialogUserManual[] = {
//  { WINDOW_CreateIndirect, "User Manual", 0, 0, 0, 480, 222, FRAMEWIN_CF_MOVEABLE },
//  { TEXT_CreateIndirect, "Core: STM32429", ID_TEXT_CORE, 10, 55, 200, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "CPU Speed : up to 180MHz", ID_TEXT_CPU, 10, 75, 200, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "Firmware Version : 1.0", ID_TEXT_VERSION, 10, 95, 200, 20, 0, 0x0, 0 },
//};



/**
  * @brief  callback for System Information
  * @param  pMsg: Pointer to Date structure
  * @retval None
  */
static void _cbSystemInformation(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem;
	char num[3];
	char str[40];
	char ip[20];
	int i;
	
  WT_Config_Read();
	
  WINDOW_SetBkColor(pMsg->hWin, 0x00FFFFFF);
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    //pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    //IMAGE_SetBMP(hItem, pData, FileSize);
    IMAGE_SetBitmap(hItem, &bm_logo_lzy115x84);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_COPYRIGHT);
    TEXT_SetFont(hItem,&GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "版权所有(C)路之遥科技有限公司");
   	//
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SOFTWRE);
    TEXT_SetFont(hItem,&GUI_FontHZ_Song_12);
		memset(str,0,sizeof(str));
		strcpy(str,"软件版本：");
		#ifdef HD_VERSION1
		sprintf(&str[15],"%d.%d.%d.%dA",DEF_WT_VERSION_MAIN, DEF_WT_VERSION_SUB1, DEF_WT_VERSION_SUB2, DEF_WT_VERSION_RC);
		#else
		sprintf(&str[15],"%d.%d.%d.%dB",DEF_WT_VERSION_MAIN, DEF_WT_VERSION_SUB1, DEF_WT_VERSION_SUB2, DEF_WT_VERSION_RC);
		#endif
		
    TEXT_SetText(hItem, str);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HARDWARE);
    TEXT_SetFont(hItem,&GUI_FontHZ_Song_12);
		
		#ifdef HD_VERSION1
		TEXT_SetText(hItem, "硬件版本：STM32F429 V1.0");
		#else
		TEXT_SetText(hItem, "硬件版本：STM32F429 V2.0");
		#endif
    
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEBSITE);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "http://www.lzy.cn");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MAC);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "MAC地址：");
    
		memset(str,0,40);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MACVAL);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
		sprintf(str,"%02x:%02x:%02x:%02x:%02x:%02x",WT_Config.MAC_Addr[0],WT_Config.MAC_Addr[1],WT_Config.MAC_Addr[2],WT_Config.MAC_Addr[3],WT_Config.MAC_Addr[4],WT_Config.MAC_Addr[5]);
		TEXT_SetText(hItem, str);
    
		memset(ip,0,20);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ADDR);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "无线地址：");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ADDRVAL);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
		sprintf(ip,"%d.%d.%d.%d",WT_Config.IP_Addr[0],WT_Config.IP_Addr[1],WT_Config.IP_Addr[2],WT_Config.IP_Addr[3]);
    TEXT_SetText(hItem, ip);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TUNNEL);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "无线通道：");
    
  	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TUNEVAL);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "2.4G");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BOARD);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "板卡数量：");
    
		if(SelfCheckItem.port_board_number == 0)
		{
			osMessagePut(WireSelfCheckEvent, WIRESELFCHECK_START_EVENT, 0);//开始自检
			i=100;
			while(i--)
			{
				osDelay(10);
				if(SelfCheckItem.state == 0) break;
			}
		}
		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BOARDSTAT);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem,itoa(SelfCheckItem.port_board_number,num,10)); 
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TRANSMIT);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "通信状态：");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TRANSMITSTAT);
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_12);
    TEXT_SetText(hItem, "OK");
    
    break;
  default:
    WM_DefaultProc(pMsg);
  }
}


/**
  * @brief  callback for General Settings
  * @param  pMsg: Pointer to Date structure
  * @retval None
  */

//static void _cbUserManual(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
//  uint32_t tmp = 0;
//  
//  hItem = pMsg->hWin;
//  WINDOW_SetBkColor(hItem, 0x00FFFFFF);
//  switch (pMsg->MsgId) {
//    
//  case WM_INIT_DIALOG:    
//    
//  /* Initialization of 'Board : STM324x9I' */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BOARD);
//    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
//    TEXT_SetTextColor(hItem, GUI_DARKGRAY);

//    /* Initialization of 'Core: STM32F-4 Series' */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CORE);
//    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
//    TEXT_SetTextColor(hItem, GUI_DARKGRAY);

//    /* Initialization of 'CPU Speed : 180MHz' */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CPU);
//    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
//    TEXT_SetTextColor(hItem, GUI_DARKGRAY);

//    /* Initialization of 'Firmware Version : 1.0' */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VERSION);
//    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
//    TEXT_SetTextColor(hItem, GUI_DARKGRAY);
//    TEXT_SetText(hItem, "Demo rev: 1.0.0");

//    /* ST Copyright */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_COPYRIGHT);
//    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
//    TEXT_SetTextColor(hItem, GUI_DARKGRAY);
//    
//    /* Set ST Logo */
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_LOGO);
//    //IMAGE_SetBitmap(hItem, &bmSTLogo40x20);
//    break;
//    
//  case WM_DELETE:  
//    /* Save Setting before delete settings frame */
//    
//    tmp = k_BkupRestoreParameter(CALIBRATION_GENERAL_SETTINGS_BKP);
//	
//    /* check if new settings have to be saved */
//    if(settings.d32 != tmp)
//    {
//      k_BkupSaveParameter(CALIBRATION_GENERAL_SETTINGS_BKP, settings.d32); 
//    }
//    break;    
//    
//  default:
//    WM_DefaultProc(pMsg);
//  }
//}


/**
  * @brief  Callback routine of the dialog
  * @param  pMsg: pointer to data structure of type WM_MESSAGE
  * @retval None
  */

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem, hDialog;
  
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    /* Initialization of 'System Information'  */
    hItem = pMsg->hWin;
		//FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0);    
    
    /* Initialization of 'Image' */
    //hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_INFO);
    //IMAGE_SetBitmap(hItem, &bminfo);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE);
    
		MULTIPAGE_SetFont(hItem,&GUI_FontHZ_Song_16);
   /* Create and attache the MULTIPAGE dialog windows */
    hDialog = GUI_CreateDialogBox(_aDialogSystemInformation, 
                                  GUI_COUNTOF(_aDialogSystemInformation), 
                                  &_cbSystemInformation, WM_UNATTACHED, 0, 0);
    MULTIPAGE_AddPage(hItem, hDialog, "系统信息");
    
//    hDialog = GUI_CreateDialogBox(_aDialogUserManual, 
//                                  GUI_COUNTOF(_aDialogUserManual), 
//                                  &_cbUserManual, WM_UNATTACHED, 0, 0);
//    MULTIPAGE_AddPage(hItem, hDialog, "用户手册");
    

    
    MULTIPAGE_SelectPage(hItem, 0);  
    
    break;
   
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
//WM_HWIN CreateSystemInfo(void);
//WM_HWIN CreateSystemInfo(void) {
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos)
{
  WM_HWIN hWindow;
//	WM_HWIN hItem;
	uint32_t i;
//	uint32_t index=0;
	wt_SetText_Title("");
	wt_SetText_Menu(wt_info.name);
	
  hWindow = GUI_CreateDialogBox(_aDialog, GUI_COUNTOF(_aDialog), _cbDialog, hWin, xpos, ypos);
//	hItem = WM_GetDialogItem(hWin, ID_MULTIPAGE);
	MULTIPAGE_SetDefaultFont(&GUI_FontHZ_Song_16);
	while(1)
  {
		//key detect
		if(BSP_GetKEY_State(KeyDown) == 1)
		{
			i=0;
			while(BSP_GetKEY_State(KeyDown) == 1)
			{
				i++;
				osDelay(100);
			}
			//LCD_BackLight_SetPWM(value);
			if(i < 20)	//2????
			{
				osDelay(300);
//				MULTIPAGE_SelectPage(hItem,index);
//				index++;
//				if(index==2)
//				{
//					index=0;
//				}

			}
			osDelay(100);
		}
		if(BSP_GetKEY_State(KeyCancle) == 1)
		{
				GUI_EndDialog(hWindow,0);
				KeyLed_State.wheel=0;
				wheel_value=0;
				Number_Windos = 0;
				return;
		}

		//delay
		osDelay(30); 
		GUI_Exec();
	}
}

/**
  * @brief  System info window Startup
  * @param  hWin: pointer to the parent handle.
  * @param  xpos: X position 
  * @param  ypos: Y position
  * @retval None
  */


// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
