/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "k_storage.h"
#include "wt_task_gui.h"
#include "wt_bsp_key_led.h"
#include "k_rtc.h"
#include "wt_task_wireselfcheck.h"
//#include "wt_task_wirefindpoint.h"
#include "wt_ad_app.h"

#pragma diag_suppress 870 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END
#define ID_WINDOW_0    			(GUI_ID_USER + 0x00)
#define ID_IMAGE_0    			(GUI_ID_USER + 0x01)
#define ID_IMAGE_1    			(GUI_ID_USER + 0x02)
#define ID_IMAGE_2    			(GUI_ID_USER + 0x03)
#define ID_IMAGE_3    			(GUI_ID_USER + 0x04)
#define ID_TEXT_0    				(GUI_ID_USER + 0x05)
#define ID_TEXT_1    				(GUI_ID_USER + 0x06)
#define ID_TEXT_2    				(GUI_ID_USER + 0x07)
#define ID_TEXT_3    				(GUI_ID_USER + 0x08)
#define ID_TEXT_4    				(GUI_ID_USER + 0x0A)
//#define ID_IMAGE_4    	(GUI_ID_USER + 0x0B)
#define ID_DROPDOWN_0    		(GUI_ID_USER + 0x0B)
#define ID_BUTTON_OK    		(GUI_ID_USER + 0x0C)
#define ID_BUTTON_CANCEL	 	(GUI_ID_USER + 0x0D)
//#define ID_MULTIEDIT	    	(GUI_ID_USER + 0x0E)


extern GUI_CONST_STORAGE GUI_BITMAP bm_ICO_debug;  //wujun added
extern GUI_CONST_STORAGE GUI_BITMAP bm_board_160x40;
extern GUI_CONST_STORAGE GUI_BITMAP bm_board_null_160x40;
extern char *itoa(int num, char *str, int radix);
extern uint32_t wheel_value;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos);


K_ModuleItem_Typedef  wt_debug =
{	
	8,
	"调试",
	&bm_ICO_debug,	
	//&CreateSystemInfo,
	Startup,
	0,
};


/*********************************************************************
*
*       _aDialog
*
* Purpose
*   Dialog resource using a WINDOW widget
*/
static const GUI_WIDGET_CREATE_INFO _aDialog[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 222, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image1", ID_IMAGE_0, 10, 10, 160, 40, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image2", ID_IMAGE_1, 10, 55, 160, 40, 0, 0, 0 },
	{ IMAGE_CreateIndirect, "Image3", ID_IMAGE_2, 10, 100, 160, 40, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image4", ID_IMAGE_3, 10, 145, 160, 40, 0, 0, 0 },
  { TEXT_CreateIndirect, "board1", ID_TEXT_0, 176, 20, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "board2", ID_TEXT_1, 176, 70, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "board3", ID_TEXT_2, 176, 115, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "board4", ID_TEXT_3, 176, 160, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Signal_source", ID_TEXT_4, 260, 85, 80, 30, 0, 0x0, 0 },
	{ DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 330, 85, 80, 30, 0, 0x0, 0 },
	//{ MULTIEDIT_CreateIndirect, "Port_index", ID_MULTIEDIT, 245, 65, 220, 120, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "start", ID_BUTTON_OK, 150, 200, 80, 20, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "exit", ID_BUTTON_CANCEL, 250, 200, 80, 20, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {

  WM_HWIN      hItem;
	uint32_t i;
	uint8_t sel=0;

  // USER START (Optionally insert additional variables)
  // USER END
	GUI_SetPenSize(8);
	WINDOW_SetBkColor(pMsg->hWin, 0x00FFFFFF);
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		if(SelfCheckItem.port_board_number == 0)
		{
			osMessagePut(WireSelfCheckEvent, WIRESELFCHECK_START_EVENT, 0);//开始自检
			i=100;
			while(i--)
			{
				osDelay(10);
				if(SelfCheckItem.state == 0) break;
			}
		}
		if(SelfCheckItem.port_board_number == 0)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
		}
		else if(SelfCheckItem.port_board_number == 1)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
		}
		else if(SelfCheckItem.port_board_number == 2)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
		}
		else if(SelfCheckItem.port_board_number == 3)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
			IMAGE_SetBitmap(hItem, &bm_board_null_160x40);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
			IMAGE_SetBitmap(hItem, &bm_board_160x40);
		}

    //
    // Initialization of 'board1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "1-64");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'board2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "65-128");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'board3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "129-192");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'board4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "193-256");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Port_index'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		DROPDOWN_SetFont(hItem,GUI_FONT_16_1);
		DROPDOWN_AddString(hItem, "4.5V");
    DROPDOWN_AddString(hItem, "12V");
		DROPDOWN_AddString(hItem, "400HZ");	
		DROPDOWN_AddString(hItem, "8mA");
		DROPDOWN_AddString(hItem, "1mA");	
		DROPDOWN_AddString(hItem, "100uA");	
		DROPDOWN_SetSel(hItem,0);
		AD_Update_SourceAddr(AD_SourceAddr_U45V,AD_SourceAddr_GND);
		
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
//    TEXT_SetText(hItem, " ");
//    TEXT_SetFont(hItem, GUI_FONT_D32);
//    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Image'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetText(hItem, "信号源:");
    TEXT_SetFont(hItem, &GUI_FontHZ_Song_16);
		TEXT_SetTextColor(hItem,GUI_BLUE);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetFont(hItem,&GUI_FontHZ_Song_12);
		BUTTON_SetText(hItem, "开始");
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GRAY);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
		BUTTON_SetFont(hItem,&GUI_FontHZ_Song_12);
		BUTTON_SetText(hItem, "关闭");
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
		
		case	MY_MESSAGE_DOWN://处理向下按钮事件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		if(WM_HasFocus(hItem))//选择测试模式
		{
			sel=DROPDOWN_GetSel(hItem);
			if(sel<4)
			{
				DROPDOWN_IncSel(hItem);
			}					
			else //sel>=5 
			{
				DROPDOWN_SetSel(hItem,5);		
			}						
		}
		sel=DROPDOWN_GetSel(hItem);
		switch (sel)
		{
			case 0:		AD_Update_SourceAddr(AD_SourceAddr_U45V, 		AD_SourceAddr_GND);	break;
			case 1:		AD_Update_SourceAddr(AD_SourceAddr_U12V, 		AD_SourceAddr_GND);	break;
			case 2:		AD_Update_SourceAddr(AD_SourceAddr_W400Hz, 	AD_SourceAddr_GND);	break;
			case 3:		AD_Update_SourceAddr(AD_SourceAddr_I8mA, 		AD_SourceAddr_GND);	break;
			case 4:		AD_Update_SourceAddr(AD_SourceAddr_I1mA, 		AD_SourceAddr_GND);	break;
			case 5:		AD_Update_SourceAddr(AD_SourceAddr_I100uA, 	AD_SourceAddr_GND);	break;
			default:	AD_Update_SourceAddr(AD_SourceAddr_U45V, 		AD_SourceAddr_GND);	break;
		}
		break;
		
		case	MY_MESSAGE_UP://处理向上按钮事件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		if(WM_HasFocus(hItem))//选择测试模式
		{
			sel=DROPDOWN_GetSel(hItem);
			if(sel>0)
			{
				DROPDOWN_DecSel(hItem);
			}					
			else //sel=0
			{
				DROPDOWN_SetSel(hItem,0);
			}						
		}
		sel=DROPDOWN_GetSel(hItem);
		switch (sel)
		{
			case 0:		AD_Update_SourceAddr(AD_SourceAddr_U45V, 		AD_SourceAddr_GND);	break;
			case 1:		AD_Update_SourceAddr(AD_SourceAddr_U12V, 		AD_SourceAddr_GND);	break;
			case 2:		AD_Update_SourceAddr(AD_SourceAddr_W400Hz, 	AD_SourceAddr_GND);	break;
			case 3:		AD_Update_SourceAddr(AD_SourceAddr_I8mA, 		AD_SourceAddr_GND);	break;
			case 4:		AD_Update_SourceAddr(AD_SourceAddr_I1mA, 		AD_SourceAddr_GND);	break;
			case 5:		AD_Update_SourceAddr(AD_SourceAddr_I100uA, 	AD_SourceAddr_GND);	break;
			default:	AD_Update_SourceAddr(AD_SourceAddr_U45V, 		AD_SourceAddr_GND);	break;
		}
  // USER START (Optionally insert additional message handling)
  // USER END
	case WM_PAINT://绘制边框
		GUI_SetColor(GUI_DARKGRAY);
		GUI_SetPenSize(8);
//		pensize = GUI_GetPenSize();
//		GUI_DrawRect(2,2,240,195);
//		GUI_DrawRect(240,2,478,195);
		GUI_DrawRoundedFrame(2, 2, 240, 195, 0, 4);
		GUI_DrawRoundedFrame(2, 2, 478, 195, 0, 4);
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
//WM_HWIN CreateSystemInfo(void);
//WM_HWIN CreateSystemInfo(void) {
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos)
{
  WM_HWIN hWindow;
	WM_HWIN hItem;
	WM_HWIN hParent;
	WM_MESSAGE Msg;


	wt_SetText_Title("");
	wt_SetText_Menu(wt_debug.name);
	
	PortBoard_Update_ChannelAddr(0,1); //state：0-ok, 1-板卡不存在, 3-无效地址, 4-通信异常
	hWindow = GUI_CreateDialogBox(_aDialog, GUI_COUNTOF(_aDialog), _cbDialog, hWin, xpos, ypos);
	
//	FindPoint.command = 1;
//	if(FindPoint.task_status == 0)	//0-waiting, 1-finding
//	osMessagePut(WireFindPointEvent, WIREFINDPOINT_START_EVENT, 0);//开始找点
//	else
//	FindPoint.command = 2;	//0-no operate, 1-start, 2-cancel

	while(1)
  {
		//key detect
		if(BSP_GetKEY_State(KeyCancle) == 1)
		{	
			PortBoard_Update_ChannelAddr(AD_ChannelAddr_NULL,AD_ChannelAddr_NULL); //state：0-ok, 1-板卡不存在, 3-无效地址, 4-通信异常
			AD_Update_SourceAddr(AD_SourceAddr_GNDR, AD_SourceAddr_GNDR);
			GUI_EndDialog(hWindow,0);
			KeyLed_State.wheel=0;
			wheel_value=0;
			Number_Windos = 0;
//			FindPoint.command = 2;
			return;
		}
		if(BSP_GetKEY_State(KeyOK) == 1)
		{
				while(BSP_GetKEY_State(KeyOK) == 1)
				{
					osDelay(10);
				}

		}
		if(BSP_GetKEY_State(KeyDown) == 1)
		{
			while(BSP_GetKEY_State(KeyDown) == 1)
			{
				osDelay(10);
			}
			
			Msg.MsgId = MY_MESSAGE_DOWN;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			WM_SendMessage(hParent,&Msg);
			
		}
		if(BSP_GetKEY_State(KeyUp) == 1)
		{
			while(BSP_GetKEY_State(KeyUp) == 1)
			{
				osDelay(10);
			}
			
			Msg.MsgId = MY_MESSAGE_UP;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			WM_SendMessage(hParent,&Msg);
			
		}

		//delay
		osDelay(30); 
		GUI_Exec();
	}
}



// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
