/*******************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "k_storage.h"
#include "wt_task_gui.h"
#include "wt_bsp_key_led.h"
#include "wt_bsp_file.h"
#include "k_bsp.h" 

#pragma diag_suppress 870 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     	(GUI_ID_USER + 0x00)
//#define ID_IMAGE_0     	(GUI_ID_USER + 0x02)
#define ID_TEXT_OK     		(GUI_ID_USER + 0x01)
#define ID_TEXT_CANCEL  	(GUI_ID_USER + 0x02)
#define ID_LISTVIEW_0     (GUI_ID_USER + 0x03)
#define ID_BUTTON_OK     	(GUI_ID_USER + 0x04)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x05)

// USER START (Optionally insert additional defines)

// USER END

extern GUI_CONST_STORAGE GUI_BITMAP bm_ICO_edit;  //wujun added
extern WM_HWIN Create_EditDlgWindow(WM_HWIN hWin_para);
extern WM_HWIN CreateMessageBox(WM_HWIN hWin_para);
extern WM_HWIN Create_EditSaveDlgWindow( WM_HWIN hWin_para);
extern WM_HWIN CreateWarningBox(WM_HWIN hWin_para);

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
#define DEF_LENGTH_ITEM_STUDY	256
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos);
void Save_editfile( WM_HWIN hWindow);

static WM_HWIN hWindow;
static uint8_t win_stat=1;//0--close window  1--not close window
extern uint32_t wheel_value;
//static char editinfo[50];
static uint16_t items_index[DEF_LENGTH_ITEM_STUDY];
static uint32_t items_show;
static uint16_t listview_FirstItem = 0;
static uint8_t edit_stat=0;//0-not sutdy  1- study ok
static uint8_t edit_stat_last=0;//0-not sutdy  1- study ok
static uint8_t  IsNewState =0;

void update_table_edit(void);
void update_item_edit(int16_t *index);
K_ModuleItem_Typedef  wt_edit =
{	
	2,
	"编辑",
	&bm_ICO_edit,	
	//&CreateSystemInfo,
	Startup,
	0,
};

extern char *itoa(int num, char *str, int radix);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 222, 0, 0x0, 0 },
	{ LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 0, 480, 204, 0, 0x0, 0 },
	//{ TEXT_CreateIndirect, "保存", ID_TEXT_OK, 170, 200, 60, 20, 0, 0x0, 0 },  
  //{ TEXT_CreateIndirect, "关闭", ID_TEXT_CANCEL,  250, 202, 60, 20, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "保存", ID_BUTTON_OK, 150, 202, 80, 20, 0, 0x0, 0 },  
	{ BUTTON_CreateIndirect, "关闭", ID_BUTTON_CANCEL, 250, 202, 80, 20, 0, 0x0, 0 },  
  //{ IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 121, 19, 207, 186, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
  // USER END
	HEADER_Handle hHeader;
  WM_HWIN      hItem;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		hHeader = LISTVIEW_GetHeader(hItem);
		//HEADER_SetTextColor(hHeader, GUI_GREEN);
		HEADER_SetFont(hHeader,&GUI_FontHZ_Song_12);
		HEADER_SetHeight(hHeader,20);
    LISTVIEW_AddColumn(hItem, 60, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "测试类型", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "节点", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "节点", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 180, "测试参数", GUI_TA_HCENTER | GUI_TA_VCENTER);
    //LISTVIEW_SetAutoScrollV(hItem, 1);
		LISTVIEW_SetGridVis(hItem,1);
		LISTVIEW_SetDefaultGridColor(GUI_GRAY);
    LISTVIEW_SetRowHeight(hItem, 20);
		LISTVIEW_EnableSort(hItem);
		LISTVIEW_SetFont(hItem, &GUI_FontHZ_Song_16);

		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetFont(hItem,&GUI_FontHZ_Song_12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GREEN);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
		BUTTON_SetFont(hItem,&GUI_FontHZ_Song_12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);
    break;
	case MY_MESSAGE_BUTTONOK:
		wt_SetText_Menu(wt_edit.name);
		KeyLed_State.wheel=0;
		edit_stat=1;
		break;
	case MY_MESSAGE_BUTTONCANCEL:
		edit_stat=0;
		KeyLed_State.wheel=0;
		break;
	case MY_MESSAGE_OK:
		GUI_EndDialog(pMsg->hWin,0);
		win_stat=0;//0--close window  1--not close window
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//WM_HWIN CreateSystemInfo(void);
//WM_HWIN CreateSystemInfo(void) {
static void Startup(WM_HWIN hWin, uint16_t xpos, uint16_t ypos)
{
 // WM_HWIN hWindow;
  WM_HWIN hItem;
	WM_HWIN hDialog;
	WM_HWIN hWarningbox;
	WM_HWIN hMessagebox;
	WM_MESSAGE Msg;
	WM_HWIN hParent;
	uint32_t i;
	int32_t wheel_stat=0;
	KeyLed_State.wheel=0;
	uint8_t buf8=0;
	listview_FirstItem = 0;
	
	int32_t  number_wheel = KeyLed_State.wheel;
	int16_t  index_item = 0;
	uint8_t tmp[2];
	int16_t len=0;
	
	wt_SetText_Title("");
	wt_SetText_Menu(wt_edit.name);
	//wt_SetText_Status("准备自学习");
	
  hWindow = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin, xpos, ypos);
	
	//创建告警对话框
	if(k_StorageGetStatus(USB_DISK_UNIT) == 0 && k_StorageGetStatus(MSD_DISK_UNIT) == 0)	
	{
		TestFile.item_total=0;
		hMessagebox = CreateMessageBox(hWindow);
		WM_BringToTop(hMessagebox);
		while(WM_IsWindow(hMessagebox))
		{
			if(BSP_GetKEY_State(KeyOK) == 1 )//wujun added 
			{
				while(BSP_GetKEY_State(KeyOK) == 1)
				{
					osDelay(10);
				}
				Msg.MsgId = MY_MESSAGE_OK;
				Msg.hWinSrc=hWindow;
				hItem=WM_GetFocussedWindow();
				hParent=hMessagebox;
				WM_SendMessage(hParent,&Msg);
			}
			GUI_Delay(20);
		}
		buf8 = 1;
	}
	else
	{
		//创建测试文件选择对话框
		hDialog=Create_EditDlgWindow(hWindow);
		
		while (WM_IsWindow(hDialog))
		{
			if(BSP_GetKEY_State(KeyOK) == 1 )//wujun added 
			{
				while(BSP_GetKEY_State(KeyOK) == 1)
				{
					osDelay(10);
				}
				hItem = WM_GetDialogItem(hWindow, ID_BUTTON_OK);
				BUTTON_SetText(hItem,"SD卡复制");
				
				Msg.MsgId = MY_MESSAGE_OK;
				Msg.hWinSrc=hWindow;
				hItem=WM_GetFocussedWindow();
				hParent=hDialog;
				WM_SendMessage(hParent,&Msg);
				buf8 = 0;
				
			}
			if(BSP_GetKEY_State(KeyCancle) == 1 ) 
			{
				while(BSP_GetKEY_State(KeyCancle) == 1)
				{
					osDelay(10);
				}
				FM25V_IO_Read(tmp,0,2);
				len = (tmp[0] << 8 ) + tmp[1];
				if(TestFile.item_total<=0 && len >0)
				{
					hItem = WM_GetDialogItem(hWindow, ID_BUTTON_OK);
					BUTTON_SetText(hItem,"SD卡复制");
				}
				
				Msg.MsgId = MY_MESSAGE_CANCEL;
				Msg.hWinSrc=hWindow;
				hItem=WM_GetFocussedWindow();
				hParent=WM_GetParent(hItem);
				WM_SendMessage(hParent,&Msg);	
				buf8 = 2;
			}
			if(BSP_GetKEY_State(KeyWheel) == 1 )//改变控件焦点
			{
				i=0;
				while(BSP_GetKEY_State(KeyWheel) == 1)
				{
					i++;
					osDelay(100);
				}
				if(i < 12)
				{
					Msg.MsgId = MY_MESSAGE_CLICK;
					hItem=WM_GetFocussedWindow();
					hParent=hDialog;
					WM_SendMessage(hParent,&Msg);
				}
				else
				{
					Msg.MsgId = MY_MESSAGE_BUTTONDELETE;
					hItem=WM_GetFocussedWindow();
					hParent=hDialog;
					WM_SendMessage(hParent,&Msg);
				}
			}
		
			if(BSP_GetKEY_State(KeyDown) == 1)
			{
				buf8 = 10;
				while(BSP_GetKEY_State(KeyDown) == 1)
				{
					osDelay(20);
					buf8--;
					if(buf8 == 0) break;
				}
				Msg.MsgId = MY_MESSAGE_DOWN;
				hItem=WM_GetFocussedWindow();
				hParent=WM_GetParent(hItem);
				WM_SendMessage(hParent,&Msg);
			}
			
			if(BSP_GetKEY_State(KeyUp) == 1)
			{
				buf8 = 10;
				while(BSP_GetKEY_State(KeyUp) == 1)
				{
					osDelay(20);
					buf8--;
					if(buf8 == 0) break;
				}
				Msg.MsgId = MY_MESSAGE_UP;
				WM_SendMessage(hDialog,&Msg);
			}
			if(KeyLed_State.wheel!=wheel_stat)//处理滚轮事件
			{
				if(wheel_stat<KeyLed_State.wheel)//顺时针旋转，向下选择条目
				{
					Msg.MsgId = MY_MESSAGE_DOWN;
					WM_SendMessage(hDialog,&Msg);
				}
				else//逆时针旋转，向上选择条目
				{
					Msg.MsgId = MY_MESSAGE_UP;
					WM_SendMessage(hDialog,&Msg);
				}
				wheel_stat=KeyLed_State.wheel;
			}
		
			GUI_Delay(20);
		 }
	 }
	
	hItem = WM_GetDialogItem(hWindow, ID_LISTVIEW_0);
	WM_SetFocus(hItem);
	 
	while(1)
  {
		//update status
		if(edit_stat != edit_stat_last)
		{
			IsNewState = 1;
			edit_stat_last = edit_stat;
		}
		//key detect
		//向下选择条目
		if(BSP_GetKEY_State(KeyDown) == 1)
		{
			hItem = WM_GetDialogItem(hWindow, ID_LISTVIEW_0);
			buf8 = 5;
			while(BSP_GetKEY_State(KeyDown) == 1)
			{
				osDelay(20);
				buf8--;
				if(buf8 == 0) break;
			}
			index_item++;
		}
		//向上选择条目
		if(BSP_GetKEY_State(KeyUp) == 1)
		{
			buf8 = 5;
			while(BSP_GetKEY_State(KeyUp) == 1)
			{
				osDelay(20);
				buf8--;
				if(buf8 == 0) break;
			}
			index_item--;
		}
		if(KeyLed_State.wheel!=number_wheel)//处理滚轮事件
		{
			index_item += KeyLed_State.wheel - number_wheel;
			number_wheel = KeyLed_State.wheel;
		}
		//保存编辑文件
		if(BSP_GetKEY_State(KeyOK) == 1 )
		{
			while(BSP_GetKEY_State(KeyOK) == 1)
			{
				osDelay(10);
			}
			FM25V_IO_Read(tmp,0,2);
			len = (tmp[0] << 8 ) + tmp[1];
			if(TestFile.item_total>0 || len >0)
			{
				KeyLed_State.wheel=0;
				Save_editfile(hWindow);//打开文件保存路径对话框
			}
//			if(TestFile.item_total<=0 && len >0)
//			{
//				hItem = WM_GetDialogItem(hWindow, ID_BUTTON_OK);
//				BUTTON_SetText(hItem,"SD卡复制");
//				KeyLed_State.wheel=0;
//				Save_editfile(hWindow);//打开文件保存路径对话框
//			}
		}
		//关闭测试程序
		if(BSP_GetKEY_State(KeyCancle) == 1  )
		{
			//弹出告警对话框
			while(BSP_GetKEY_State(KeyCancle) == 1)
			{
				osDelay(10);
			}
			hWarningbox = CreateWarningBox(hWindow);			
			//WM_BringToTop(hWarningbox);
			//WM_SetFocus(hWarningbox);
			GUI_Exec();
			win_stat=1;
			while(WM_IsWindow(hWarningbox))
			{
				if(BSP_GetKEY_State(KeyOK) == 1 )//确定关闭
				{
					while(BSP_GetKEY_State(KeyOK) == 1)
					{
						osDelay(10);
					}
					
					Msg.MsgId = MY_MESSAGE_OK;
					Msg.hWinSrc = hWindow;
					hItem=WM_GetFocussedWindow();
					//hParent=WM_GetParent(hItem);
					hParent=hWarningbox;
					KeyLed_State.wheel=0;
					wheel_value=0;
					TestFile.item_total=0;
					edit_stat=0;
					edit_stat_last=0;
					WM_SendMessage(hParent,&Msg);
					if(win_stat != 1  )//0--close window  1--not close window
					{						
						Number_Windos = 0;
						return;
					}
					
				}
				if(BSP_GetKEY_State(KeyCancle) == 1 )//取消关闭
				{
					while(BSP_GetKEY_State(KeyCancle) == 1)
					{
						osDelay(10);
					}
					GUI_EndDialog(hWarningbox,0);
					GUI_Exec();
				}
				osDelay(10);
			}		
			
			osDelay(30);
		}
		
		if(TestFile.item_total<=0)
		{			
			hItem = WM_GetDialogItem(hWindow, ID_BUTTON_OK);
			TEXT_SetText(hItem,(char *)"自学习");
		}
		else
		{
			hItem = WM_GetDialogItem(hWindow, ID_BUTTON_OK);
			TEXT_SetText(hItem,(char *)"保存");
		}
		
		if(edit_stat == 1)
		{
			edit_stat = 0;
			update_table_edit();
		} 
		
		update_item_edit(&index_item);
		//delay
		osDelay(30); 
		GUI_Exec();
	}
}

//保存学习文件，打开保存路径对话框
void Save_editfile( WM_HWIN hWindow)
{
  WM_HWIN hItem;
	WM_HWIN hDialog;
	WM_MESSAGE Msg;
	WM_HWIN hParent;
	uint32_t i;
	uint32_t wheel_stat=0;
	
	wt_SetText_Status("保存编辑文件");

	hDialog=Create_EditSaveDlgWindow(hWindow);
	while(WM_IsWindow(hDialog))
	{
		if(BSP_GetKEY_State(KeyOK) == 1)//wujun added 
		{
			i=0;
			Msg.MsgId = MY_MESSAGE_OK;
			hItem=WM_GetFocussedWindow();
			//hParent=WM_GetParent(hItem);
			hParent=hDialog;
			while(BSP_GetKEY_State(KeyOK) == 1)
			{
				i++;
				osDelay(100);
			}
			if(i < 20)
			{
				WM_SendMessage(hParent,&Msg);	
				osDelay(100);					
			}
			hItem = WM_GetDialogItem(hWindow, ID_LISTVIEW_0);
			WM_SetFocus(hItem);
		}
		//取消并关闭窗口
		if(BSP_GetKEY_State(KeyCancle) == 1 )
		{
			i=0;
			while(BSP_GetKEY_State(KeyCancle) == 1)
			{
				i++;
				osDelay(100);
			}
			if(i < 20)
			{
				GUI_EndDialog(hDialog,0);
				GUI_Exec();
			}
			hItem = WM_GetDialogItem(hWindow, ID_LISTVIEW_0);
			WM_SetFocus(hItem);
		}
		if(BSP_GetKEY_State(KeyUp) == 1 )//wujun added 
		{
			i=0;
			Msg.MsgId = MY_MESSAGE_UP;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			//WM_SendMessage(hParent,&Msg);
			
			while(BSP_GetKEY_State(KeyUp) == 1)
			{
				i++;
				osDelay(100);
			}
			if(i < 20)
			{
				WM_SendMessage(hParent,&Msg);
				GUI_Delay(300);
			}
		}
		if(BSP_GetKEY_State(KeyDown) == 1 )//wujun added 
		{
			i=0;
			Msg.MsgId = MY_MESSAGE_DOWN;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			//WM_SendMessage(hParent,&Msg);
			
			while(BSP_GetKEY_State(KeyDown) == 1)
			{
				i++;
				osDelay(300);
			}
			if(i < 20)
			{
				WM_SendMessage(hParent,&Msg);
				GUI_Delay(100);
			}
		}
		if(KeyLed_State.wheel!=wheel_stat)//处理滚轮事件
		{
			Msg.MsgId = MY_MESSAGE_WHEEL;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			WM_SendMessage(hParent,&Msg);
			wheel_stat=KeyLed_State.wheel;
		}
		//wheel按键删除字符
		if(BSP_GetKEY_State(KeyWheel) == 1 )
		{
			Msg.MsgId = MY_MESSAGE_BUTTONDELETE;
			Msg.hWinSrc = hWindow;
			hItem=WM_GetFocussedWindow();
			hParent=WM_GetParent(hItem);
			//WM_SendMessage(hParent,&Msg);
			while(BSP_GetKEY_State(KeyWheel) == 1)
			{
				i++;
				osDelay(100);
			}
			if(i < 20)
			{
				WM_SendMessage(hParent,&Msg);
				//osDelay(100);
			}
		}	
		GUI_Delay(100);			
	}
}



//更新WRDC类型结构体,显示自学习条目
void update_table_edit(void)
{
	uint32_t i;
	uint32_t buf32;
	
	for(i=0;i<DEF_LENGTH_ITEM_STUDY;i++) items_index[i]=0;
	
	//过滤断路条目
	buf32 = 0;
	for(i=0;i<TestFile.item_total;i++)
	{
		if(TestFile.test_item[i].type=='Z')
		{
			continue;
		}
		else 
		{
			if(buf32 < DEF_LENGTH_ITEM_STUDY) items_index[buf32]=i;
			buf32++;
		}
	}
	items_show = buf32;
}

//更新WRDC显示
void update_item_edit(int16_t *index)
{
	WM_HWIN  hItem;
	uint8_t  buf8;
	uint16_t buf16;
	uint16_t i;
	static uint32_t items_study_show_last=0;

	const char * pText[2][5];
	char id[5];
	char p1[5];
	char p2[5];
	char param[20];
	
	hItem = WM_GetDialogItem(hWindow, ID_LISTVIEW_0);
	if(items_show <= 0) 
	{
		*index=0;
		//delete items
		while(1)
		{
			buf8 = LISTVIEW_GetNumRows(hItem);
			if(buf8 != 0) LISTVIEW_DeleteRow(hItem,0);
			else break;
		}
		return;
	}
	// check index
	if(*index < 0) *index=0;
	
	else if(*index >= items_show) *index = items_show-1;
	
	
	//更新整个控件
	if(IsNewState != 0 || items_study_show_last != items_show)
	{
		IsNewState = 0;
		items_study_show_last = items_show;
		while(1)
		{
			buf8 = LISTVIEW_GetNumRows(hItem);
			if(buf8 != 0) LISTVIEW_DeleteRow(hItem,0);
			else break;
		}
		
		if(items_show > 9) 	buf8 = 9;
		else								buf8 = items_show;
		for(i=0;i<buf8;i++)
		{
			buf16 = i;
			itoa(buf16+1,id,10);
			pText[0][0]=id;

			//itoa(TestFile.test_item[items_index[buf16]].p1,p1,10);
			num_converter(TestFile.test_item[items_index[buf16]].p1,p1);
			pText[0][2]=p1;
			//itoa(TestFile.test_item[items_index[buf16]].p2,p2,10);
			num_converter(TestFile.test_item[items_index[buf16]].p2,p2);
			pText[0][3]=p2;

			if(TestFile.test_item[items_index[buf16]].type=='W')
			{
				pText[0][1]="导通";
				sprintf(param,"RGB=%d%d%d",TestFile.test_item[items_index[buf16]].param1,TestFile.test_item[items_index[buf16]].param2,TestFile.test_item[items_index[buf16]].param3);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='D')
			{
				pText[0][1]="二极管";
				sprintf(param,"V=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='C')
			{
				pText[0][1]="电容";
				sprintf(param,"C=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='R')
			{
				pText[0][1]="电阻";
				sprintf(param,"R=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='Z')
			{
				pText[0][1]="断路";
				sprintf(param,"Z=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else
			{
				pText[0][1]="开关";
				sprintf(param,"K=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			pText[0][4]=param;
			
			LISTVIEW_AddRow(hItem,pText[0]);
		}
		LISTVIEW_SetSel(hItem,0);
	}
	if(*index < listview_FirstItem)	//显示上移
	{
		//delete item
		buf8 = listview_FirstItem - *index;
		if(buf8 > 9) buf8=9;
		for(i=0;i<buf8;i++) LISTVIEW_DeleteRow(hItem,8-i);
		
		if(listview_FirstItem > buf8)  listview_FirstItem -= buf8;
		else															listview_FirstItem = 0;

		//add item
		for(i=0;i<buf8;i++)
		{
			//buf16 = *index + buf8 - 1 - i;
			if(buf16 >= DEF_LENGTH_ITEM_STUDY) 	buf16 = DEF_LENGTH_ITEM_STUDY - 1;
			else 										buf16 = *index + buf8 - 1 - i;
			itoa(buf16+1,id,10);
			pText[0][0]=id;

			//itoa(TestFile.test_item[items_index[buf16]].p1,p1,10);
			num_converter(TestFile.test_item[items_index[buf16]].p1,p1);
			pText[0][2]=p1;
			//itoa(TestFile.test_item[items_index[buf16]].p2,p2,10);
			num_converter(TestFile.test_item[items_index[buf16]].p2,p2);
			pText[0][3]=p2;

			if(TestFile.test_item[items_index[buf16]].type=='W')
			{
				pText[0][1]="导通";
				sprintf(param,"RGB=%d%d%d",TestFile.test_item[items_index[buf16]].param1,TestFile.test_item[items_index[buf16]].param2,TestFile.test_item[items_index[buf16]].param3);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='D')
			{
				pText[0][1]="二极管";
				sprintf(param,"V=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='C')
			{
				pText[0][1]="电容";
				sprintf(param,"C=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='R')
			{
				pText[0][1]="电阻";
				sprintf(param,"R=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='Z')
			{
				pText[0][1]="断路";
				sprintf(param,"Z=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else
			{
				pText[0][1]="开关";
				sprintf(param,"K=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			pText[0][4]=param;
			
			LISTVIEW_InsertRow(hItem, 0, pText[0]);
		}
		LISTVIEW_SetSel(hItem,0);
	}
	else if(*index > listview_FirstItem +8)	//显示下移
	{
		//delete item
		buf8 = *index - listview_FirstItem - 8;
		if(buf8 > 9) buf8=9;
		for(i=0;i<buf8;i++) LISTVIEW_DeleteRow(hItem,0);
		listview_FirstItem += buf8;

		//add item
		for(i=0;i<buf8;i++)
		{
			//buf16 = *index - buf8 + 1 + i;
			if(buf16 >= DEF_LENGTH_ITEM_STUDY) 	buf16 = DEF_LENGTH_ITEM_STUDY - 1;
			else 										buf16 = *index - buf8 + 1 + i;
			itoa(buf16+1,id,10);
			pText[1][0]=id;

			//itoa(TestFile.test_item[items_index[buf16]].p1,p1,10);
			num_converter(TestFile.test_item[items_index[buf16]].p1,p1);
			pText[1][2]=p1;
			//itoa(TestFile.test_item[items_index[buf16]].p2,p2,10);
			num_converter(TestFile.test_item[items_index[buf16]].p1,p1);
			pText[1][3]=p2;

			if(TestFile.test_item[items_index[buf16]].type=='W')
			{
				pText[1][1]="导通";
				sprintf(param,"RGB=%d%d%d",TestFile.test_item[items_index[buf16]].param1,TestFile.test_item[items_index[buf16]].param2,TestFile.test_item[items_index[buf16]].param3);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='D')
			{
				pText[1][1]="二极管";
				sprintf(param,"V=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='C')
			{
				pText[1][1]="电容";
				sprintf(param,"C=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='R')
			{
				pText[1][1]="电阻";
				sprintf(param,"R=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else if(TestFile.test_item[items_index[buf16]].type=='Z')
			{
				pText[1][1]="断路";
				sprintf(param,"Z=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			else
			{
				pText[1][1]="开关";
				sprintf(param,"K=%d",TestFile.test_item[items_index[buf16]].param1);
			}
			pText[1][4]=param;
			
			LISTVIEW_AddRow(hItem,pText[1]);
		}
		LISTVIEW_SetSel(hItem,9);
	}
	else	//修改指针
	{
		LISTVIEW_SetSel(hItem,(*index - listview_FirstItem));
	}

}



// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
